[core]
workspace_base = "/tmp/run_arvo_local_secbench_oss_libxml2.ossfuzz-42484562_mg3nadm8/workspace"
cache_dir = "/tmp/run_arvo_local_secbench_oss_libxml2.ossfuzz-42484562_mg3nadm8/results/secbench_oss_libxml2.ossfuzz-42484562-890b3431779447c091ef2ef3e6334cdb/cache"
file_store_path = "/tmp/run_arvo_local_secbench_oss_libxml2.ossfuzz-42484562_mg3nadm8/results/secbench_oss_libxml2.ossfuzz-42484562-890b3431779447c091ef2ef3e6334cdb/file"
save_trajectory_path = "/tmp/run_arvo_local_secbench_oss_libxml2.ossfuzz-42484562_mg3nadm8/results/secbench_oss_libxml2.ossfuzz-42484562-890b3431779447c091ef2ef3e6334cdb/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
base_url = ""
temperature = 0.0
top_p = 1.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
