[core]
workspace_base = "/tmp/run_arvo_42495340_eaq1n4qf/tmp/arvo_42495340-8078102008304781ac1aca419450f9e3/workspace"
cache_dir = "/tmp/run_arvo_42495340_eaq1n4qf/results/arvo_42495340-8078102008304781ac1aca419450f9e3/cache"
file_store_path = "/tmp/run_arvo_42495340_eaq1n4qf/results/arvo_42495340-8078102008304781ac1aca419450f9e3/file"
save_trajectory_path = "/tmp/run_arvo_42495340_eaq1n4qf/results/arvo_42495340-8078102008304781ac1aca419450f9e3/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
