[core]
workspace_base = "/tmp/run_arvo_14232_di3jyapy/tmp/arvo_14232-b52648a3d7ef4186afbb9e4030e08727/workspace"
cache_dir = "/tmp/run_arvo_14232_di3jyapy/results/arvo_14232-b52648a3d7ef4186afbb9e4030e08727/cache"
file_store_path = "/tmp/run_arvo_14232_di3jyapy/results/arvo_14232-b52648a3d7ef4186afbb9e4030e08727/file"
save_trajectory_path = "/tmp/run_arvo_14232_di3jyapy/results/arvo_14232-b52648a3d7ef4186afbb9e4030e08727/trajectory"
run_as_openhands = false

[llm]
model = "claude-opus-4-6"
max_output_tokens = 2048
base_url = "https://api.lmuai.com"
custom_llm_provider = "anthropic"
top_p = 1.0
temperature = 0.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
