[core]
workspace_base = "/tmp/run_arvo_local_osv_ossfuzz_OSV-2026-195__ufn7yje/workspace"
cache_dir = "/tmp/run_arvo_local_osv_ossfuzz_OSV-2026-195__ufn7yje/results/osv_ossfuzz_OSV-2026-195-b870b64fb5344a6c9701be333d2c1146/cache"
file_store_path = "/tmp/run_arvo_local_osv_ossfuzz_OSV-2026-195__ufn7yje/results/osv_ossfuzz_OSV-2026-195-b870b64fb5344a6c9701be333d2c1146/file"
save_trajectory_path = "/tmp/run_arvo_local_osv_ossfuzz_OSV-2026-195__ufn7yje/results/osv_ossfuzz_OSV-2026-195-b870b64fb5344a6c9701be333d2c1146/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
base_url = ""
top_p = 1.0
temperature = 0.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
