[core]
workspace_base = "/tmp/run_arvo_42539076_dta9hz_j/tmp/arvo_42539076-42732a14c1e1439c9a5601e7dfae499a/workspace"
cache_dir = "/tmp/run_arvo_42539076_dta9hz_j/results/arvo_42539076-42732a14c1e1439c9a5601e7dfae499a/cache"
file_store_path = "/tmp/run_arvo_42539076_dta9hz_j/results/arvo_42539076-42732a14c1e1439c9a5601e7dfae499a/file"
save_trajectory_path = "/tmp/run_arvo_42539076_dta9hz_j/results/arvo_42539076-42732a14c1e1439c9a5601e7dfae499a/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
