[core]
workspace_base = "/tmp/run_arvo_28462_6g0mic_v/tmp/arvo_28462-c62160d4cd8042f4b8620c66a8615eff/workspace"
cache_dir = "/tmp/run_arvo_28462_6g0mic_v/results/arvo_28462-c62160d4cd8042f4b8620c66a8615eff/cache"
file_store_path = "/tmp/run_arvo_28462_6g0mic_v/results/arvo_28462-c62160d4cd8042f4b8620c66a8615eff/file"
save_trajectory_path = "/tmp/run_arvo_28462_6g0mic_v/results/arvo_28462-c62160d4cd8042f4b8620c66a8615eff/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
