[core]
workspace_base = "/tmp/run_arvo_10216_6kjqjs9b/tmp/arvo_10216-a293f373a53047ae82d43b4e80eaa4e1/workspace"
cache_dir = "/tmp/run_arvo_10216_6kjqjs9b/results/arvo_10216-a293f373a53047ae82d43b4e80eaa4e1/cache"
file_store_path = "/tmp/run_arvo_10216_6kjqjs9b/results/arvo_10216-a293f373a53047ae82d43b4e80eaa4e1/file"
save_trajectory_path = "/tmp/run_arvo_10216_6kjqjs9b/results/arvo_10216-a293f373a53047ae82d43b4e80eaa4e1/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.5-2026-04-24"
max_output_tokens = 2048
base_url = "https://aidp.bytedance.net/api/modelhub/online/v2/crawl/openai/deployments/gpt-5.5-2026-04-24/chat/completions?api-version=2024-03-01-preview"
api_version = "2024-03-01-preview"
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
