[core]
workspace_base = "/tmp/run_arvo_14565_6g7m20sw/tmp/arvo_14565-c5a11c9b891d41ae8458c0d549addf9a/workspace"
cache_dir = "/tmp/run_arvo_14565_6g7m20sw/results/arvo_14565-c5a11c9b891d41ae8458c0d549addf9a/cache"
file_store_path = "/tmp/run_arvo_14565_6g7m20sw/results/arvo_14565-c5a11c9b891d41ae8458c0d549addf9a/file"
save_trajectory_path = "/tmp/run_arvo_14565_6g7m20sw/results/arvo_14565-c5a11c9b891d41ae8458c0d549addf9a/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.4-mini"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
