[core]
workspace_base = "/tmp/run_arvo_10143_fojk17pe/tmp/arvo_10143-7be21d1cc6f04b0a9664f1bddaba9658/workspace"
cache_dir = "/tmp/run_arvo_10143_fojk17pe/results/arvo_10143-7be21d1cc6f04b0a9664f1bddaba9658/cache"
file_store_path = "/tmp/run_arvo_10143_fojk17pe/results/arvo_10143-7be21d1cc6f04b0a9664f1bddaba9658/file"
save_trajectory_path = "/tmp/run_arvo_10143_fojk17pe/results/arvo_10143-7be21d1cc6f04b0a9664f1bddaba9658/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
