[core]
workspace_base = "/tmp/run_arvo_14625_n5p9vf7j/tmp/arvo_14625-f766cb094bf043448cbdad6e41fe2964/workspace"
cache_dir = "/tmp/run_arvo_14625_n5p9vf7j/results/arvo_14625-f766cb094bf043448cbdad6e41fe2964/cache"
file_store_path = "/tmp/run_arvo_14625_n5p9vf7j/results/arvo_14625-f766cb094bf043448cbdad6e41fe2964/file"
save_trajectory_path = "/tmp/run_arvo_14625_n5p9vf7j/results/arvo_14625-f766cb094bf043448cbdad6e41fe2964/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
