[core]
workspace_base = "/tmp/run_arvo_20906_0q_8tuh_/tmp/arvo_20906-fd7c9bebdd1a498b8d637b6a0d4e6802/workspace"
cache_dir = "/tmp/run_arvo_20906_0q_8tuh_/results/arvo_20906-fd7c9bebdd1a498b8d637b6a0d4e6802/cache"
file_store_path = "/tmp/run_arvo_20906_0q_8tuh_/results/arvo_20906-fd7c9bebdd1a498b8d637b6a0d4e6802/file"
save_trajectory_path = "/tmp/run_arvo_20906_0q_8tuh_/results/arvo_20906-fd7c9bebdd1a498b8d637b6a0d4e6802/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
