[core]
workspace_base = "/tmp/run_arvo_42504982_3i4zh1gf/tmp/arvo_42504982-65f9cc53258b4b96970f3aa88ea3ecad/workspace"
cache_dir = "/tmp/run_arvo_42504982_3i4zh1gf/results/arvo_42504982-65f9cc53258b4b96970f3aa88ea3ecad/cache"
file_store_path = "/tmp/run_arvo_42504982_3i4zh1gf/results/arvo_42504982-65f9cc53258b4b96970f3aa88ea3ecad/file"
save_trajectory_path = "/tmp/run_arvo_42504982_3i4zh1gf/results/arvo_42504982-65f9cc53258b4b96970f3aa88ea3ecad/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
base_url = ""
top_p = 1.0
temperature = 0.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
