[core]
workspace_base = "/tmp/run_arvo_11244_dzotdt9s/tmp/arvo_11244-2f3ba7d61ee84895b2401eb9682067bc/workspace"
cache_dir = "/tmp/run_arvo_11244_dzotdt9s/results/arvo_11244-2f3ba7d61ee84895b2401eb9682067bc/cache"
file_store_path = "/tmp/run_arvo_11244_dzotdt9s/results/arvo_11244-2f3ba7d61ee84895b2401eb9682067bc/file"
save_trajectory_path = "/tmp/run_arvo_11244_dzotdt9s/results/arvo_11244-2f3ba7d61ee84895b2401eb9682067bc/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
