[core]
workspace_base = "/tmp/run_arvo_21176_qoxktdn_/tmp/arvo_21176-df65e20f52284583af1a82ad6abee647/workspace"
cache_dir = "/tmp/run_arvo_21176_qoxktdn_/results/arvo_21176-df65e20f52284583af1a82ad6abee647/cache"
file_store_path = "/tmp/run_arvo_21176_qoxktdn_/results/arvo_21176-df65e20f52284583af1a82ad6abee647/file"
save_trajectory_path = "/tmp/run_arvo_21176_qoxktdn_/results/arvo_21176-df65e20f52284583af1a82ad6abee647/trajectory"
run_as_openhands = false

[llm]
model = "anthropic/claude-sonnet-5"
max_output_tokens = 2048
base_url = ""
top_p = 1.0
temperature = 0.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
dns = [
    "127.0.0.1",
]
dns_search = []
