[core]
workspace_base = "/tmp/run_arvo_31425_hoxupyje/tmp/arvo_31425-546d7f3ec8ff4e58b7febd1a2000556b/workspace"
cache_dir = "/tmp/run_arvo_31425_hoxupyje/results/arvo_31425-546d7f3ec8ff4e58b7febd1a2000556b/cache"
file_store_path = "/tmp/run_arvo_31425_hoxupyje/results/arvo_31425-546d7f3ec8ff4e58b7febd1a2000556b/file"
save_trajectory_path = "/tmp/run_arvo_31425_hoxupyje/results/arvo_31425-546d7f3ec8ff4e58b7febd1a2000556b/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
