[core]
workspace_base = "/tmp/run_arvo_45636_d_yzw7o5/tmp/arvo_45636-81b37823a5ce458893ef28c3d63c323c/workspace"
cache_dir = "/tmp/run_arvo_45636_d_yzw7o5/results/arvo_45636-81b37823a5ce458893ef28c3d63c323c/cache"
file_store_path = "/tmp/run_arvo_45636_d_yzw7o5/results/arvo_45636-81b37823a5ce458893ef28c3d63c323c/file"
save_trajectory_path = "/tmp/run_arvo_45636_d_yzw7o5/results/arvo_45636-81b37823a5ce458893ef28c3d63c323c/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
