[core]
workspace_base = "/tmp/run_arvo_13704_ji6x7xms/tmp/arvo_13704-d8bc0c8ec7c74f9198e6855c72365330/workspace"
cache_dir = "/tmp/run_arvo_13704_ji6x7xms/results/arvo_13704-d8bc0c8ec7c74f9198e6855c72365330/cache"
file_store_path = "/tmp/run_arvo_13704_ji6x7xms/results/arvo_13704-d8bc0c8ec7c74f9198e6855c72365330/file"
save_trajectory_path = "/tmp/run_arvo_13704_ji6x7xms/results/arvo_13704-d8bc0c8ec7c74f9198e6855c72365330/trajectory"
run_as_openhands = false

[llm]
model = "claude-opus-4-6"
max_output_tokens = 2048
base_url = "https://api.lmuai.com"
custom_llm_provider = "anthropic"
top_p = 1.0
temperature = 0.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
