[core]
workspace_base = "/tmp/run_arvo_18448_j_sov3fv/tmp/arvo_18448-badf0e6bc4b6498e9aa0894bfb58cb6d/workspace"
cache_dir = "/tmp/run_arvo_18448_j_sov3fv/results/arvo_18448-badf0e6bc4b6498e9aa0894bfb58cb6d/cache"
file_store_path = "/tmp/run_arvo_18448_j_sov3fv/results/arvo_18448-badf0e6bc4b6498e9aa0894bfb58cb6d/file"
save_trajectory_path = "/tmp/run_arvo_18448_j_sov3fv/results/arvo_18448-badf0e6bc4b6498e9aa0894bfb58cb6d/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.4-mini"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
