[core]
workspace_base = "/tmp/run_arvo_25364_1sjuuncf/tmp/arvo_25364-a3d9bde4474d4d5b8bb05065f89b534f/workspace"
cache_dir = "/tmp/run_arvo_25364_1sjuuncf/results/arvo_25364-a3d9bde4474d4d5b8bb05065f89b534f/cache"
file_store_path = "/tmp/run_arvo_25364_1sjuuncf/results/arvo_25364-a3d9bde4474d4d5b8bb05065f89b534f/file"
save_trajectory_path = "/tmp/run_arvo_25364_1sjuuncf/results/arvo_25364-a3d9bde4474d4d5b8bb05065f89b534f/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
