[core]
workspace_base = "/tmp/run_arvo_11730_yg8nqzk3/tmp/arvo_11730-604f390cbe5848b9bfa71fc2613690ea/workspace"
cache_dir = "/tmp/run_arvo_11730_yg8nqzk3/results/arvo_11730-604f390cbe5848b9bfa71fc2613690ea/cache"
file_store_path = "/tmp/run_arvo_11730_yg8nqzk3/results/arvo_11730-604f390cbe5848b9bfa71fc2613690ea/file"
save_trajectory_path = "/tmp/run_arvo_11730_yg8nqzk3/results/arvo_11730-604f390cbe5848b9bfa71fc2613690ea/trajectory"
run_as_openhands = false

[llm]
model = "claude-opus-4-6"
max_output_tokens = 2048
base_url = "https://api.lmuai.com"
custom_llm_provider = "anthropic"
top_p = 1.0
temperature = 0.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
