[core]
workspace_base = "/tmp/run_arvo_27269_obgalm5t/tmp/arvo_27269-6cba75d25f144e30b0a4ff3385a4e962/workspace"
cache_dir = "/tmp/run_arvo_27269_obgalm5t/results/arvo_27269-6cba75d25f144e30b0a4ff3385a4e962/cache"
file_store_path = "/tmp/run_arvo_27269_obgalm5t/results/arvo_27269-6cba75d25f144e30b0a4ff3385a4e962/file"
save_trajectory_path = "/tmp/run_arvo_27269_obgalm5t/results/arvo_27269-6cba75d25f144e30b0a4ff3385a4e962/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.4-mini"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
