[core]
workspace_base = "/tmp/run_arvo_local_secbench_oss_php.ossfuzz-42527736_dch232d0/workspace"
cache_dir = "/tmp/run_arvo_local_secbench_oss_php.ossfuzz-42527736_dch232d0/results/secbench_oss_php.ossfuzz-42527736-a8ab7a50e4cb487b95ff6467d5266a38/cache"
file_store_path = "/tmp/run_arvo_local_secbench_oss_php.ossfuzz-42527736_dch232d0/results/secbench_oss_php.ossfuzz-42527736-a8ab7a50e4cb487b95ff6467d5266a38/file"
save_trajectory_path = "/tmp/run_arvo_local_secbench_oss_php.ossfuzz-42527736_dch232d0/results/secbench_oss_php.ossfuzz-42527736-a8ab7a50e4cb487b95ff6467d5266a38/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.5-2026-04-24"
max_output_tokens = 2048
base_url = "https://aidp.bytedance.net/api/modelhub/online/v2/crawl/openai/deployments/gpt-5.5-2026-04-24/chat/completions?api-version=2024-03-01-preview"
api_version = "2024-03-01-preview"
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
