[core]
workspace_base = "/tmp/run_arvo_4112_1v282d8r/tmp/arvo_4112-490ec690fc694c33a3f98c433e279076/workspace"
cache_dir = "/tmp/run_arvo_4112_1v282d8r/results/arvo_4112-490ec690fc694c33a3f98c433e279076/cache"
file_store_path = "/tmp/run_arvo_4112_1v282d8r/results/arvo_4112-490ec690fc694c33a3f98c433e279076/file"
save_trajectory_path = "/tmp/run_arvo_4112_1v282d8r/results/arvo_4112-490ec690fc694c33a3f98c433e279076/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
