[core]
workspace_base = "/tmp/run_arvo_10865_xucpxjx_/tmp/arvo_10865-8115d892f14141b2aef5edf138d0d60b/workspace"
cache_dir = "/tmp/run_arvo_10865_xucpxjx_/results/arvo_10865-8115d892f14141b2aef5edf138d0d60b/cache"
file_store_path = "/tmp/run_arvo_10865_xucpxjx_/results/arvo_10865-8115d892f14141b2aef5edf138d0d60b/file"
save_trajectory_path = "/tmp/run_arvo_10865_xucpxjx_/results/arvo_10865-8115d892f14141b2aef5edf138d0d60b/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.4-mini"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
