#!/usr/bin/env python3
"""GT coverage tracker: which samples are done, which are partial, which remain.

Scans gt_results/ against the dataset's sample universe and classifies every
sample as:
  * complete   -- has the core GT artifacts AND passes the deterministic gates
                  (root_cause_criterion binding + field_bindings/event_locations
                  coverage). Only these are recorded as "done".
  * incomplete -- a gt_results/ dir exists but is missing artifacts or fails a
                  gate (should be re-run).
  * remaining  -- no gt_results/ dir yet (not started).

Writes GT_STATUS.md (overwritten each run) so a collaborator can see at a glance
what is already generated and what they should run next. Run it standalone, or
let gt_plugin.py call it before a batch to refresh the doc and skip done samples.

    python3 gt_generation/gt_status.py
    python3 gt_generation/gt_status.py --selection dataset/selected_1000.json
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

CODE_ROOT = Path(__file__).resolve().parent
REPO_ROOT = CODE_ROOT.parent
GT_RESULTS = REPO_ROOT / "gt_results"
STATUS_DOC = REPO_ROOT / "GT_STATUS.md"

# The core artifacts a complete fine-grained GT must have (the 15-file package's
# load-bearing subset -- the rest are traces/poc/build that the gates imply).
CORE_FILES = (
    "ground_truth.json",
    "verified_assertions.json",
    "verified_invariants.json",
    "field_bindings.json",
    "event_locations.json",
    "reachability_report.json",
)

sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(CODE_ROOT))


def _display_path(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def classify(sample_id: str) -> tuple[str, str]:
    """Return (status, detail) for one sample: 'complete' | 'incomplete' | 'remaining'."""
    d = GT_RESULTS / sample_id
    if not d.is_dir():
        return "remaining", "not started"
    missing = [f for f in CORE_FILES if not (d / f).is_file()]
    if missing:
        return "incomplete", f"missing {', '.join(missing)}"

    try:
        # Run the same final package audit as Stage 05. The audit package is
        # the final GT contract; generation_timing is diagnostic and can be
        # stale after manual repair or package cleanup.
        from gt_toolkit.package_audit import audit_package
        audit = audit_package(d)
        if not audit.get("ok"):
            errors = audit.get("errors") or ["package audit failed"]
            return "incomplete", f"package audit: {str(errors[0])[:120]}"
    except Exception as exc:
        return "incomplete", f"gate error: {type(exc).__name__}: {exc}"
    return "complete", "ok"


def scan(sample_ids: list[str]) -> dict[str, list[tuple[str, str]]]:
    buckets: dict[str, list[tuple[str, str]]] = {"complete": [], "incomplete": [], "remaining": []}
    for sid in sample_ids:
        status, detail = classify(sid)
        buckets[status].append((sid, detail))
    return buckets


def _load_sample_ids(selection: Path) -> list[str]:
    data = json.loads(selection.read_text())
    if isinstance(data, dict):
        samples = data.get("samples") or []
    else:
        samples = data
    ids: list[str] = []
    for value in samples:
        if isinstance(value, dict) and value.get("sample_id"):
            ids.append(str(value["sample_id"]))
        elif isinstance(value, str) and value:
            ids.append(value)
    return ids


def write_status_doc(buckets: dict[str, list[tuple[str, str]]], total: int, selection: Path) -> None:
    complete = sorted(s for s, _ in buckets["complete"])
    incomplete = sorted(buckets["incomplete"])
    remaining = sorted(s for s, _ in buckets["remaining"])
    lines = [
        "# GT generation status",
        "",
        "_Auto-generated by `gt_generation/gt_status.py` — do not edit by hand._",
        f"_Universe: {total} samples in `{_display_path(selection)}`._",
        "",
        f"- **complete (recorded, do not re-run): {len(complete)}**",
        f"- incomplete (started, needs re-run): {len(incomplete)}",
        f"- remaining (not started): {len(remaining)}",
        "",
        "## Complete",
        "",
        "These have valid fine-grained GT and are recorded as done:",
        "",
        ("".join(f"- {s}\n" for s in complete) or "- (none)\n"),
        "## Incomplete — re-run these",
        "",
        "A gt_results dir exists but is missing artifacts or fails a gate:",
        "",
        ("".join(f"- {s} — {detail}\n" for s, detail in incomplete) or "- (none)\n"),
        "## Remaining — not started",
        "",
        f"{len(remaining)} samples have no gt_results yet. Collaborators should run these "
        "(any not in the Complete list). First 40:",
        "",
        ("".join(f"- {s}\n" for s in remaining[:40]) or "- (none)\n"),
    ]
    STATUS_DOC.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--selection", type=Path, default=REPO_ROOT / "dataset" / "selected_1000.json")
    ap.add_argument("--quiet", action="store_true", help="Only write the doc, no stdout table.")
    args = ap.parse_args(argv)

    sample_ids = _load_sample_ids(args.selection)
    buckets = scan(sample_ids)
    write_status_doc(buckets, len(sample_ids), args.selection)

    if not args.quiet:
        print(f"complete={len(buckets['complete'])}  incomplete={len(buckets['incomplete'])}  "
              f"remaining={len(buckets['remaining'])}  (of {len(sample_ids)})")
        for sid, detail in sorted(buckets["incomplete"]):
            print(f"  incomplete: {sid} — {detail}")
    print(f"wrote {STATUS_DOC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
