[core]
workspace_base = "/tmp/run_arvo_42496071_12km1ude/tmp/arvo_42496071-cb455a5fa0e64806931fd4eadf3aafbb/workspace"
cache_dir = "/tmp/run_arvo_42496071_12km1ude/results/arvo_42496071-cb455a5fa0e64806931fd4eadf3aafbb/cache"
file_store_path = "/tmp/run_arvo_42496071_12km1ude/results/arvo_42496071-cb455a5fa0e64806931fd4eadf3aafbb/file"
save_trajectory_path = "/tmp/run_arvo_42496071_12km1ude/results/arvo_42496071-cb455a5fa0e64806931fd4eadf3aafbb/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.4-mini-2026-03-17"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = "https://aidp.bytedance.net/api/modelhub/online/v2/crawl/openai/deployments/gpt-5.4-mini-2026-03-17/chat/completions?api-version=2024-03-01-preview"
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
