[core]
workspace_base = "/tmp/run_arvo_18890__c8wju1r/tmp/arvo_18890-12d6d986350f4b018475bf0265dd9137/workspace"
cache_dir = "/tmp/run_arvo_18890__c8wju1r/results/arvo_18890-12d6d986350f4b018475bf0265dd9137/cache"
file_store_path = "/tmp/run_arvo_18890__c8wju1r/results/arvo_18890-12d6d986350f4b018475bf0265dd9137/file"
save_trajectory_path = "/tmp/run_arvo_18890__c8wju1r/results/arvo_18890-12d6d986350f4b018475bf0265dd9137/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
