[core]
workspace_base = "/tmp/run_arvo_17119_sopbpbxo/tmp/arvo_17119-648ba366de614b5ea14cf0f6027418fa/workspace"
cache_dir = "/tmp/run_arvo_17119_sopbpbxo/results/arvo_17119-648ba366de614b5ea14cf0f6027418fa/cache"
file_store_path = "/tmp/run_arvo_17119_sopbpbxo/results/arvo_17119-648ba366de614b5ea14cf0f6027418fa/file"
save_trajectory_path = "/tmp/run_arvo_17119_sopbpbxo/results/arvo_17119-648ba366de614b5ea14cf0f6027418fa/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.4-mini"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
