[core]
workspace_base = "/tmp/run_arvo_42506130_06a0s5vy/tmp/arvo_42506130-525afb6b9c1748f58569fa5ac93d50fa/workspace"
cache_dir = "/tmp/run_arvo_42506130_06a0s5vy/results/arvo_42506130-525afb6b9c1748f58569fa5ac93d50fa/cache"
file_store_path = "/tmp/run_arvo_42506130_06a0s5vy/results/arvo_42506130-525afb6b9c1748f58569fa5ac93d50fa/file"
save_trajectory_path = "/tmp/run_arvo_42506130_06a0s5vy/results/arvo_42506130-525afb6b9c1748f58569fa5ac93d50fa/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
