[core]
workspace_base = "/tmp/run_arvo_26325_nsyrc2kk/tmp/arvo_26325-ce936e7fe623463a91d91a1dc6b382d0/workspace"
cache_dir = "/tmp/run_arvo_26325_nsyrc2kk/results/arvo_26325-ce936e7fe623463a91d91a1dc6b382d0/cache"
file_store_path = "/tmp/run_arvo_26325_nsyrc2kk/results/arvo_26325-ce936e7fe623463a91d91a1dc6b382d0/file"
save_trajectory_path = "/tmp/run_arvo_26325_nsyrc2kk/results/arvo_26325-ce936e7fe623463a91d91a1dc6b382d0/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.4-mini"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
