[core]
workspace_base = "/Users/bytedance/Downloads/code_zxr/GT_generation/poc_generation/tmp/arvo_1304-f6c29a41476842c196ba4b80698c37dd/workspace"
cache_dir = "/Users/bytedance/Downloads/code_zxr/GT_generation/poc_generation/results/arvo_1304-f6c29a41476842c196ba4b80698c37dd/cache"
file_store_path = "/Users/bytedance/Downloads/code_zxr/GT_generation/poc_generation/results/arvo_1304-f6c29a41476842c196ba4b80698c37dd/file"
save_trajectory_path = "/Users/bytedance/Downloads/code_zxr/GT_generation/poc_generation/results/arvo_1304-f6c29a41476842c196ba4b80698c37dd/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
