[core]
workspace_base = "/tmp/run_arvo_42512152_bgddyl5u/tmp/arvo_42512152-e35ca37c8df342cf9656453f398c1853/workspace"
cache_dir = "/tmp/run_arvo_42512152_bgddyl5u/results/arvo_42512152-e35ca37c8df342cf9656453f398c1853/cache"
file_store_path = "/tmp/run_arvo_42512152_bgddyl5u/results/arvo_42512152-e35ca37c8df342cf9656453f398c1853/file"
save_trajectory_path = "/tmp/run_arvo_42512152_bgddyl5u/results/arvo_42512152-e35ca37c8df342cf9656453f398c1853/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.4-mini-2026-03-17"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = "https://aidp.bytedance.net/api/modelhub/online/v2/crawl/openai/deployments/gpt-5.4-mini-2026-03-17/chat/completions?api-version=2024-03-01-preview"
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
