[core]
workspace_base = "/tmp/run_arvo_12953_tp12m64h/tmp/arvo_12953-d6d9150f6f144b439127fa98d122933a/workspace"
cache_dir = "/tmp/run_arvo_12953_tp12m64h/results/arvo_12953-d6d9150f6f144b439127fa98d122933a/cache"
file_store_path = "/tmp/run_arvo_12953_tp12m64h/results/arvo_12953-d6d9150f6f144b439127fa98d122933a/file"
save_trajectory_path = "/tmp/run_arvo_12953_tp12m64h/results/arvo_12953-d6d9150f6f144b439127fa98d122933a/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.4-mini"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
