[core]
workspace_base = "/tmp/run_arvo_22094_bszf0u9x/tmp/arvo_22094-1d392f02d06c4d6a8911fed683f73021/workspace"
cache_dir = "/tmp/run_arvo_22094_bszf0u9x/results/arvo_22094-1d392f02d06c4d6a8911fed683f73021/cache"
file_store_path = "/tmp/run_arvo_22094_bszf0u9x/results/arvo_22094-1d392f02d06c4d6a8911fed683f73021/file"
save_trajectory_path = "/tmp/run_arvo_22094_bszf0u9x/results/arvo_22094-1d392f02d06c4d6a8911fed683f73021/trajectory"
run_as_openhands = false

[llm]
model = "anthropic/claude-sonnet-5"
max_output_tokens = 2048
base_url = ""
top_p = 1.0
temperature = 0.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
dns = [
    "127.0.0.1",
]
dns_search = []
