[core]
workspace_base = "/var/folders/np/t4qxz4811lldn6bfqh_sh46c0000gn/T/run_arvo_13359_7shqtwi8/tmp/arvo_13359-095167d1f1bf47c5800e4d1693078f8b/workspace"
cache_dir = "/var/folders/np/t4qxz4811lldn6bfqh_sh46c0000gn/T/run_arvo_13359_7shqtwi8/results/arvo_13359-095167d1f1bf47c5800e4d1693078f8b/cache"
file_store_path = "/var/folders/np/t4qxz4811lldn6bfqh_sh46c0000gn/T/run_arvo_13359_7shqtwi8/results/arvo_13359-095167d1f1bf47c5800e4d1693078f8b/file"
save_trajectory_path = "/var/folders/np/t4qxz4811lldn6bfqh_sh46c0000gn/T/run_arvo_13359_7shqtwi8/results/arvo_13359-095167d1f1bf47c5800e4d1693078f8b/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
