[core]
workspace_base = "/tmp/run_arvo_local_secbench_oss_libxml2.ossfuzz-42522712_hk7pcycu/workspace"
cache_dir = "/tmp/run_arvo_local_secbench_oss_libxml2.ossfuzz-42522712_hk7pcycu/results/secbench_oss_libxml2.ossfuzz-42522712-8f89c08f2d14487daf8c37bd88d1267a/cache"
file_store_path = "/tmp/run_arvo_local_secbench_oss_libxml2.ossfuzz-42522712_hk7pcycu/results/secbench_oss_libxml2.ossfuzz-42522712-8f89c08f2d14487daf8c37bd88d1267a/file"
save_trajectory_path = "/tmp/run_arvo_local_secbench_oss_libxml2.ossfuzz-42522712_hk7pcycu/results/secbench_oss_libxml2.ossfuzz-42522712-8f89c08f2d14487daf8c37bd88d1267a/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
base_url = ""
top_p = 1.0
temperature = 0.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
