[core]
workspace_base = "/tmp/run_arvo_33991_ulhaih48/tmp/arvo_33991-e3e6500091a14a26b42010f0b088eac0/workspace"
cache_dir = "/tmp/run_arvo_33991_ulhaih48/results/arvo_33991-e3e6500091a14a26b42010f0b088eac0/cache"
file_store_path = "/tmp/run_arvo_33991_ulhaih48/results/arvo_33991-e3e6500091a14a26b42010f0b088eac0/file"
save_trajectory_path = "/tmp/run_arvo_33991_ulhaih48/results/arvo_33991-e3e6500091a14a26b42010f0b088eac0/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
