[core]
workspace_base = "/tmp/run_arvo_local_secbench_oss_mruby.ossfuzz-401868632_ols_k4x0/workspace"
cache_dir = "/tmp/run_arvo_local_secbench_oss_mruby.ossfuzz-401868632_ols_k4x0/results/secbench_oss_mruby.ossfuzz-401868632-7bbf1aaf6b5f4026b102b67ec563aa81/cache"
file_store_path = "/tmp/run_arvo_local_secbench_oss_mruby.ossfuzz-401868632_ols_k4x0/results/secbench_oss_mruby.ossfuzz-401868632-7bbf1aaf6b5f4026b102b67ec563aa81/file"
save_trajectory_path = "/tmp/run_arvo_local_secbench_oss_mruby.ossfuzz-401868632_ols_k4x0/results/secbench_oss_mruby.ossfuzz-401868632-7bbf1aaf6b5f4026b102b67ec563aa81/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
base_url = ""
temperature = 0.0
top_p = 1.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
