[core]
workspace_base = "/tmp/run_arvo_18261_2kr_u6t9/tmp/arvo_18261-a10b20dcd9934316bd9fe14f6e33a733/workspace"
cache_dir = "/tmp/run_arvo_18261_2kr_u6t9/results/arvo_18261-a10b20dcd9934316bd9fe14f6e33a733/cache"
file_store_path = "/tmp/run_arvo_18261_2kr_u6t9/results/arvo_18261-a10b20dcd9934316bd9fe14f6e33a733/file"
save_trajectory_path = "/tmp/run_arvo_18261_2kr_u6t9/results/arvo_18261-a10b20dcd9934316bd9fe14f6e33a733/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.4-mini"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
