[core]
workspace_base = "/tmp/run_arvo_42479042_q9wlavz_/tmp/arvo_42479042-7b3ef63a83184cac820451024a02f515/workspace"
cache_dir = "/tmp/run_arvo_42479042_q9wlavz_/results/arvo_42479042-7b3ef63a83184cac820451024a02f515/cache"
file_store_path = "/tmp/run_arvo_42479042_q9wlavz_/results/arvo_42479042-7b3ef63a83184cac820451024a02f515/file"
save_trajectory_path = "/tmp/run_arvo_42479042_q9wlavz_/results/arvo_42479042-7b3ef63a83184cac820451024a02f515/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
