[core]
workspace_base = "/tmp/run_arvo_36025_l104z8bd/tmp/arvo_36025-c94f5b3bafad4d2996b54637afcc8d7d/workspace"
cache_dir = "/tmp/run_arvo_36025_l104z8bd/results/arvo_36025-c94f5b3bafad4d2996b54637afcc8d7d/cache"
file_store_path = "/tmp/run_arvo_36025_l104z8bd/results/arvo_36025-c94f5b3bafad4d2996b54637afcc8d7d/file"
save_trajectory_path = "/tmp/run_arvo_36025_l104z8bd/results/arvo_36025-c94f5b3bafad4d2996b54637afcc8d7d/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
