[core]
workspace_base = "/tmp/run_arvo_15374_xhz2a8da/tmp/arvo_15374-28a4580769734d348ebebbded356362e/workspace"
cache_dir = "/tmp/run_arvo_15374_xhz2a8da/results/arvo_15374-28a4580769734d348ebebbded356362e/cache"
file_store_path = "/tmp/run_arvo_15374_xhz2a8da/results/arvo_15374-28a4580769734d348ebebbded356362e/file"
save_trajectory_path = "/tmp/run_arvo_15374_xhz2a8da/results/arvo_15374-28a4580769734d348ebebbded356362e/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
