[core]
workspace_base = "/tmp/run_arvo_53046_tzpujak3/tmp/arvo_53046-94157d2437574c1da6bb479d81f5381e/workspace"
cache_dir = "/tmp/run_arvo_53046_tzpujak3/results/arvo_53046-94157d2437574c1da6bb479d81f5381e/cache"
file_store_path = "/tmp/run_arvo_53046_tzpujak3/results/arvo_53046-94157d2437574c1da6bb479d81f5381e/file"
save_trajectory_path = "/tmp/run_arvo_53046_tzpujak3/results/arvo_53046-94157d2437574c1da6bb479d81f5381e/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
