[core]
workspace_base = "/tmp/run_arvo_18066_njycgk0_/tmp/arvo_18066-5c6e34c55be245d2938bd0570192d008/workspace"
cache_dir = "/tmp/run_arvo_18066_njycgk0_/results/arvo_18066-5c6e34c55be245d2938bd0570192d008/cache"
file_store_path = "/tmp/run_arvo_18066_njycgk0_/results/arvo_18066-5c6e34c55be245d2938bd0570192d008/file"
save_trajectory_path = "/tmp/run_arvo_18066_njycgk0_/results/arvo_18066-5c6e34c55be245d2938bd0570192d008/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
