[core]
workspace_base = "/tmp/run_arvo_17170_jjl0x7yu/tmp/arvo_17170-d885d82510034981ba6dd5a937378a65/workspace"
cache_dir = "/tmp/run_arvo_17170_jjl0x7yu/results/arvo_17170-d885d82510034981ba6dd5a937378a65/cache"
file_store_path = "/tmp/run_arvo_17170_jjl0x7yu/results/arvo_17170-d885d82510034981ba6dd5a937378a65/file"
save_trajectory_path = "/tmp/run_arvo_17170_jjl0x7yu/results/arvo_17170-d885d82510034981ba6dd5a937378a65/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
