[core]
workspace_base = "/tmp/run_arvo_34152_rrswo1g5/tmp/arvo_34152-5fadf7c3c0634a1b9257d92051bf745f/workspace"
cache_dir = "/tmp/run_arvo_34152_rrswo1g5/results/arvo_34152-5fadf7c3c0634a1b9257d92051bf745f/cache"
file_store_path = "/tmp/run_arvo_34152_rrswo1g5/results/arvo_34152-5fadf7c3c0634a1b9257d92051bf745f/file"
save_trajectory_path = "/tmp/run_arvo_34152_rrswo1g5/results/arvo_34152-5fadf7c3c0634a1b9257d92051bf745f/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
