[core]
workspace_base = "/tmp/run_arvo_42275__5m4uhem/tmp/arvo_42275-2b2e484e8c6742f48ccbcb5fba3ab65d/workspace"
cache_dir = "/tmp/run_arvo_42275__5m4uhem/results/arvo_42275-2b2e484e8c6742f48ccbcb5fba3ab65d/cache"
file_store_path = "/tmp/run_arvo_42275__5m4uhem/results/arvo_42275-2b2e484e8c6742f48ccbcb5fba3ab65d/file"
save_trajectory_path = "/tmp/run_arvo_42275__5m4uhem/results/arvo_42275-2b2e484e8c6742f48ccbcb5fba3ab65d/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
