[core]
workspace_base = "/tmp/run_arvo_42516681_jqoy0w08/tmp/arvo_42516681-f351c11cb4d648548507cd814210ee74/workspace"
cache_dir = "/tmp/run_arvo_42516681_jqoy0w08/results/arvo_42516681-f351c11cb4d648548507cd814210ee74/cache"
file_store_path = "/tmp/run_arvo_42516681_jqoy0w08/results/arvo_42516681-f351c11cb4d648548507cd814210ee74/file"
save_trajectory_path = "/tmp/run_arvo_42516681_jqoy0w08/results/arvo_42516681-f351c11cb4d648548507cd814210ee74/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.5-2026-04-24"
max_output_tokens = 2048
base_url = "https://aidp.bytedance.net/api/modelhub/online/v2/crawl/openai/deployments/gpt-5.5-2026-04-24/chat/completions?api-version=2024-03-01-preview"
api_version = "2024-03-01-preview"
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
dns = [
    "127.0.0.1",
]
dns_search = []
