[core]
workspace_base = "/tmp/run_arvo_31332_zq30k5fx/tmp/arvo_31332-86a60b1893a24ae69b7f900716ec5f3a/workspace"
cache_dir = "/tmp/run_arvo_31332_zq30k5fx/results/arvo_31332-86a60b1893a24ae69b7f900716ec5f3a/cache"
file_store_path = "/tmp/run_arvo_31332_zq30k5fx/results/arvo_31332-86a60b1893a24ae69b7f900716ec5f3a/file"
save_trajectory_path = "/tmp/run_arvo_31332_zq30k5fx/results/arvo_31332-86a60b1893a24ae69b7f900716ec5f3a/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
