[core]
workspace_base = "/tmp/run_arvo_42483053_bsdva65a/tmp/arvo_42483053-415e7d7ef36b41be82c0f705f6f29f15/workspace"
cache_dir = "/tmp/run_arvo_42483053_bsdva65a/results/arvo_42483053-415e7d7ef36b41be82c0f705f6f29f15/cache"
file_store_path = "/tmp/run_arvo_42483053_bsdva65a/results/arvo_42483053-415e7d7ef36b41be82c0f705f6f29f15/file"
save_trajectory_path = "/tmp/run_arvo_42483053_bsdva65a/results/arvo_42483053-415e7d7ef36b41be82c0f705f6f29f15/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
