[core]
workspace_base = "/tmp/run_arvo_12466_3rcsm574/tmp/arvo_12466-f767ffb32f8d49e88915382cb9b3e883/workspace"
cache_dir = "/tmp/run_arvo_12466_3rcsm574/results/arvo_12466-f767ffb32f8d49e88915382cb9b3e883/cache"
file_store_path = "/tmp/run_arvo_12466_3rcsm574/results/arvo_12466-f767ffb32f8d49e88915382cb9b3e883/file"
save_trajectory_path = "/tmp/run_arvo_12466_3rcsm574/results/arvo_12466-f767ffb32f8d49e88915382cb9b3e883/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
