[core]
workspace_base = "/tmp/run_arvo_37211_b3h8kxlt/tmp/arvo_37211-8184a235978c4e50ad000142cd10507e/workspace"
cache_dir = "/tmp/run_arvo_37211_b3h8kxlt/results/arvo_37211-8184a235978c4e50ad000142cd10507e/cache"
file_store_path = "/tmp/run_arvo_37211_b3h8kxlt/results/arvo_37211-8184a235978c4e50ad000142cd10507e/file"
save_trajectory_path = "/tmp/run_arvo_37211_b3h8kxlt/results/arvo_37211-8184a235978c4e50ad000142cd10507e/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
