[core]
workspace_base = "/tmp/run_arvo_12959_m7tnu_5o/tmp/arvo_12959-a1f9e912d6834f7dbb99c3b0b9f0a40c/workspace"
cache_dir = "/tmp/run_arvo_12959_m7tnu_5o/results/arvo_12959-a1f9e912d6834f7dbb99c3b0b9f0a40c/cache"
file_store_path = "/tmp/run_arvo_12959_m7tnu_5o/results/arvo_12959-a1f9e912d6834f7dbb99c3b0b9f0a40c/file"
save_trajectory_path = "/tmp/run_arvo_12959_m7tnu_5o/results/arvo_12959-a1f9e912d6834f7dbb99c3b0b9f0a40c/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.4-mini"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
