[core]
workspace_base = "/tmp/run_arvo_20321_sw5u4w3o/tmp/arvo_20321-f5e5ed3351ef4f2daa51e93152ca3116/workspace"
cache_dir = "/tmp/run_arvo_20321_sw5u4w3o/results/arvo_20321-f5e5ed3351ef4f2daa51e93152ca3116/cache"
file_store_path = "/tmp/run_arvo_20321_sw5u4w3o/results/arvo_20321-f5e5ed3351ef4f2daa51e93152ca3116/file"
save_trajectory_path = "/tmp/run_arvo_20321_sw5u4w3o/results/arvo_20321-f5e5ed3351ef4f2daa51e93152ca3116/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
