[core]
workspace_base = "/tmp/run_arvo_26674_vn_r73uk/tmp/arvo_26674-1f6f13f5cc1443708c824933c5a94c2e/workspace"
cache_dir = "/tmp/run_arvo_26674_vn_r73uk/results/arvo_26674-1f6f13f5cc1443708c824933c5a94c2e/cache"
file_store_path = "/tmp/run_arvo_26674_vn_r73uk/results/arvo_26674-1f6f13f5cc1443708c824933c5a94c2e/file"
save_trajectory_path = "/tmp/run_arvo_26674_vn_r73uk/results/arvo_26674-1f6f13f5cc1443708c824933c5a94c2e/trajectory"
run_as_openhands = false

[llm]
model = "anthropic/claude-sonnet-5"
max_output_tokens = 2048
base_url = ""
top_p = 1.0
temperature = 0.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
dns = [
    "127.0.0.1",
]
dns_search = []
