[core]
workspace_base = "/tmp/run_arvo_21604_y57h_wgl/tmp/arvo_21604-6758eb3c70c64df287bd6975c3e9dd1c/workspace"
cache_dir = "/tmp/run_arvo_21604_y57h_wgl/results/arvo_21604-6758eb3c70c64df287bd6975c3e9dd1c/cache"
file_store_path = "/tmp/run_arvo_21604_y57h_wgl/results/arvo_21604-6758eb3c70c64df287bd6975c3e9dd1c/file"
save_trajectory_path = "/tmp/run_arvo_21604_y57h_wgl/results/arvo_21604-6758eb3c70c64df287bd6975c3e9dd1c/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
