[core]
workspace_base = "/tmp/run_arvo_30236_d3pmthvr/tmp/arvo_30236-9e0a68777d2c468c9e15b6a42d2c5150/workspace"
cache_dir = "/tmp/run_arvo_30236_d3pmthvr/results/arvo_30236-9e0a68777d2c468c9e15b6a42d2c5150/cache"
file_store_path = "/tmp/run_arvo_30236_d3pmthvr/results/arvo_30236-9e0a68777d2c468c9e15b6a42d2c5150/file"
save_trajectory_path = "/tmp/run_arvo_30236_d3pmthvr/results/arvo_30236-9e0a68777d2c468c9e15b6a42d2c5150/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.5-2026-04-24"
max_output_tokens = 2048
base_url = "https://aidp.bytedance.net/api/modelhub/online/v2/crawl/openai/deployments/gpt-5.5-2026-04-24/chat/completions?api-version=2024-03-01-preview"
api_version = "2024-03-01-preview"
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
dns = [
    "127.0.0.1",
]
dns_search = []
