[core]
workspace_base = "/tmp/run_arvo_42491502_lct7j_k9/tmp/arvo_42491502-cd5319b8d1874d30ab4b200b29b8ed8e/workspace"
cache_dir = "/tmp/run_arvo_42491502_lct7j_k9/results/arvo_42491502-cd5319b8d1874d30ab4b200b29b8ed8e/cache"
file_store_path = "/tmp/run_arvo_42491502_lct7j_k9/results/arvo_42491502-cd5319b8d1874d30ab4b200b29b8ed8e/file"
save_trajectory_path = "/tmp/run_arvo_42491502_lct7j_k9/results/arvo_42491502-cd5319b8d1874d30ab4b200b29b8ed8e/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
