[core]
workspace_base = "/tmp/run_arvo_14960_wvrd0sym/tmp/arvo_14960-4be74c98ec7e4bfcac4e95fbdb0aa35c/workspace"
cache_dir = "/tmp/run_arvo_14960_wvrd0sym/results/arvo_14960-4be74c98ec7e4bfcac4e95fbdb0aa35c/cache"
file_store_path = "/tmp/run_arvo_14960_wvrd0sym/results/arvo_14960-4be74c98ec7e4bfcac4e95fbdb0aa35c/file"
save_trajectory_path = "/tmp/run_arvo_14960_wvrd0sym/results/arvo_14960-4be74c98ec7e4bfcac4e95fbdb0aa35c/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
