[core]
workspace_base = "/tmp/run_arvo_42534594_5hier_i7/tmp/arvo_42534594-73ba81179db74bd08d9c5e7bc7c44286/workspace"
cache_dir = "/tmp/run_arvo_42534594_5hier_i7/results/arvo_42534594-73ba81179db74bd08d9c5e7bc7c44286/cache"
file_store_path = "/tmp/run_arvo_42534594_5hier_i7/results/arvo_42534594-73ba81179db74bd08d9c5e7bc7c44286/file"
save_trajectory_path = "/tmp/run_arvo_42534594_5hier_i7/results/arvo_42534594-73ba81179db74bd08d9c5e7bc7c44286/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
