[core]
workspace_base = "/tmp/run_arvo_61361_v609w56u/tmp/arvo_61361-04b4405e043b44358fec647292565639/workspace"
cache_dir = "/tmp/run_arvo_61361_v609w56u/results/arvo_61361-04b4405e043b44358fec647292565639/cache"
file_store_path = "/tmp/run_arvo_61361_v609w56u/results/arvo_61361-04b4405e043b44358fec647292565639/file"
save_trajectory_path = "/tmp/run_arvo_61361_v609w56u/results/arvo_61361-04b4405e043b44358fec647292565639/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
