[core]
workspace_base = "/tmp/run_arvo_42534761_64x1cir6/tmp/arvo_42534761-a24c31089df24ace840f88a504a2841a/workspace"
cache_dir = "/tmp/run_arvo_42534761_64x1cir6/results/arvo_42534761-a24c31089df24ace840f88a504a2841a/cache"
file_store_path = "/tmp/run_arvo_42534761_64x1cir6/results/arvo_42534761-a24c31089df24ace840f88a504a2841a/file"
save_trajectory_path = "/tmp/run_arvo_42534761_64x1cir6/results/arvo_42534761-a24c31089df24ace840f88a504a2841a/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
