[core]
workspace_base = "/tmp/run_arvo_13837_2l2_d1l9/tmp/arvo_13837-2c8037d483b94f16b51b2d3f9bd01ef3/workspace"
cache_dir = "/tmp/run_arvo_13837_2l2_d1l9/results/arvo_13837-2c8037d483b94f16b51b2d3f9bd01ef3/cache"
file_store_path = "/tmp/run_arvo_13837_2l2_d1l9/results/arvo_13837-2c8037d483b94f16b51b2d3f9bd01ef3/file"
save_trajectory_path = "/tmp/run_arvo_13837_2l2_d1l9/results/arvo_13837-2c8037d483b94f16b51b2d3f9bd01ef3/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.4-mini"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
