[core]
workspace_base = "/tmp/run_arvo_3736_19cxk73g/tmp/arvo_3736-3a1716e300ba446da8b45af4cd1f8590/workspace"
cache_dir = "/tmp/run_arvo_3736_19cxk73g/results/arvo_3736-3a1716e300ba446da8b45af4cd1f8590/cache"
file_store_path = "/tmp/run_arvo_3736_19cxk73g/results/arvo_3736-3a1716e300ba446da8b45af4cd1f8590/file"
save_trajectory_path = "/tmp/run_arvo_3736_19cxk73g/results/arvo_3736-3a1716e300ba446da8b45af4cd1f8590/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.4-mini-2026-03-17"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = "https://aidp.bytedance.net/api/modelhub/online/v2/crawl/openai/deployments/gpt-5.4-mini-2026-03-17/chat/completions?api-version=2024-03-01-preview"
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
