[core]
workspace_base = "/tmp/run_arvo_15971_4lm1139p/tmp/arvo_15971-486f5a0d20a94e5e9692e6a8909519ef/workspace"
cache_dir = "/tmp/run_arvo_15971_4lm1139p/results/arvo_15971-486f5a0d20a94e5e9692e6a8909519ef/cache"
file_store_path = "/tmp/run_arvo_15971_4lm1139p/results/arvo_15971-486f5a0d20a94e5e9692e6a8909519ef/file"
save_trajectory_path = "/tmp/run_arvo_15971_4lm1139p/results/arvo_15971-486f5a0d20a94e5e9692e6a8909519ef/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
