[core]
workspace_base = "/var/folders/np/t4qxz4811lldn6bfqh_sh46c0000gn/T/run_arvo_17119_w3oauok9/tmp/arvo_17119-3883123087b045c8869bc8b98e7c2d63/workspace"
cache_dir = "/var/folders/np/t4qxz4811lldn6bfqh_sh46c0000gn/T/run_arvo_17119_w3oauok9/results/arvo_17119-3883123087b045c8869bc8b98e7c2d63/cache"
file_store_path = "/var/folders/np/t4qxz4811lldn6bfqh_sh46c0000gn/T/run_arvo_17119_w3oauok9/results/arvo_17119-3883123087b045c8869bc8b98e7c2d63/file"
save_trajectory_path = "/var/folders/np/t4qxz4811lldn6bfqh_sh46c0000gn/T/run_arvo_17119_w3oauok9/results/arvo_17119-3883123087b045c8869bc8b98e7c2d63/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
