[core]
workspace_base = "/tmp/run_arvo_10952_c4khpvvz/tmp/arvo_10952-2df6f99063414359990180f8d2742997/workspace"
cache_dir = "/tmp/run_arvo_10952_c4khpvvz/results/arvo_10952-2df6f99063414359990180f8d2742997/cache"
file_store_path = "/tmp/run_arvo_10952_c4khpvvz/results/arvo_10952-2df6f99063414359990180f8d2742997/file"
save_trajectory_path = "/tmp/run_arvo_10952_c4khpvvz/results/arvo_10952-2df6f99063414359990180f8d2742997/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
