[core]
workspace_base = "/tmp/run_arvo_42490732_3mt4z35g/tmp/arvo_42490732-f297a0e81f744a02b7812ea65fb229de/workspace"
cache_dir = "/tmp/run_arvo_42490732_3mt4z35g/results/arvo_42490732-f297a0e81f744a02b7812ea65fb229de/cache"
file_store_path = "/tmp/run_arvo_42490732_3mt4z35g/results/arvo_42490732-f297a0e81f744a02b7812ea65fb229de/file"
save_trajectory_path = "/tmp/run_arvo_42490732_3mt4z35g/results/arvo_42490732-f297a0e81f744a02b7812ea65fb229de/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
