[core]
workspace_base = "/tmp/run_arvo_28777_3023bh48/tmp/arvo_28777-67f69e0860394ad2b3409f6b5f5e3508/workspace"
cache_dir = "/tmp/run_arvo_28777_3023bh48/results/arvo_28777-67f69e0860394ad2b3409f6b5f5e3508/cache"
file_store_path = "/tmp/run_arvo_28777_3023bh48/results/arvo_28777-67f69e0860394ad2b3409f6b5f5e3508/file"
save_trajectory_path = "/tmp/run_arvo_28777_3023bh48/results/arvo_28777-67f69e0860394ad2b3409f6b5f5e3508/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
