[core]
workspace_base = "/tmp/run_arvo_42516204_sj1a78a3/tmp/arvo_42516204-5dd4fa2e0b6046ae9a043febcafd5b97/workspace"
cache_dir = "/tmp/run_arvo_42516204_sj1a78a3/results/arvo_42516204-5dd4fa2e0b6046ae9a043febcafd5b97/cache"
file_store_path = "/tmp/run_arvo_42516204_sj1a78a3/results/arvo_42516204-5dd4fa2e0b6046ae9a043febcafd5b97/file"
save_trajectory_path = "/tmp/run_arvo_42516204_sj1a78a3/results/arvo_42516204-5dd4fa2e0b6046ae9a043febcafd5b97/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
