[core]
workspace_base = "/tmp/run_arvo_11752_meu_glij/tmp/arvo_11752-7d0cad35af4b4547ab7a2e1406a8d982/workspace"
cache_dir = "/tmp/run_arvo_11752_meu_glij/results/arvo_11752-7d0cad35af4b4547ab7a2e1406a8d982/cache"
file_store_path = "/tmp/run_arvo_11752_meu_glij/results/arvo_11752-7d0cad35af4b4547ab7a2e1406a8d982/file"
save_trajectory_path = "/tmp/run_arvo_11752_meu_glij/results/arvo_11752-7d0cad35af4b4547ab7a2e1406a8d982/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.4-mini"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
