[core]
workspace_base = "/tmp/run_arvo_local_secbench_oss_openexr.ossfuzz-42511621_bguor91p/workspace"
cache_dir = "/tmp/run_arvo_local_secbench_oss_openexr.ossfuzz-42511621_bguor91p/results/secbench_oss_openexr.ossfuzz-42511621-08947d33a7d84caa8917eba05aaffa1f/cache"
file_store_path = "/tmp/run_arvo_local_secbench_oss_openexr.ossfuzz-42511621_bguor91p/results/secbench_oss_openexr.ossfuzz-42511621-08947d33a7d84caa8917eba05aaffa1f/file"
save_trajectory_path = "/tmp/run_arvo_local_secbench_oss_openexr.ossfuzz-42511621_bguor91p/results/secbench_oss_openexr.ossfuzz-42511621-08947d33a7d84caa8917eba05aaffa1f/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
base_url = ""
top_p = 1.0
temperature = 0.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
