[core]
workspace_base = "/tmp/run_arvo_1065_ozylpuo3/tmp/arvo_1065-6d8e0c6c59da462db343df3ff3072977/workspace"
cache_dir = "/tmp/run_arvo_1065_ozylpuo3/results/arvo_1065-6d8e0c6c59da462db343df3ff3072977/cache"
file_store_path = "/tmp/run_arvo_1065_ozylpuo3/results/arvo_1065-6d8e0c6c59da462db343df3ff3072977/file"
save_trajectory_path = "/tmp/run_arvo_1065_ozylpuo3/results/arvo_1065-6d8e0c6c59da462db343df3ff3072977/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
