[core]
workspace_base = "/var/folders/np/t4qxz4811lldn6bfqh_sh46c0000gn/T/run_arvo_14467__wq0aolr/tmp/arvo_14467-bea26eaf8d174238a4c9a0717cfde9f6/workspace"
cache_dir = "/var/folders/np/t4qxz4811lldn6bfqh_sh46c0000gn/T/run_arvo_14467__wq0aolr/results/arvo_14467-bea26eaf8d174238a4c9a0717cfde9f6/cache"
file_store_path = "/var/folders/np/t4qxz4811lldn6bfqh_sh46c0000gn/T/run_arvo_14467__wq0aolr/results/arvo_14467-bea26eaf8d174238a4c9a0717cfde9f6/file"
save_trajectory_path = "/var/folders/np/t4qxz4811lldn6bfqh_sh46c0000gn/T/run_arvo_14467__wq0aolr/results/arvo_14467-bea26eaf8d174238a4c9a0717cfde9f6/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
