[core]
workspace_base = "/tmp/run_arvo_34386_aozf5kr3/tmp/arvo_34386-1ae0bcc3f813406e8d1a759ad6b5b8c5/workspace"
cache_dir = "/tmp/run_arvo_34386_aozf5kr3/results/arvo_34386-1ae0bcc3f813406e8d1a759ad6b5b8c5/cache"
file_store_path = "/tmp/run_arvo_34386_aozf5kr3/results/arvo_34386-1ae0bcc3f813406e8d1a759ad6b5b8c5/file"
save_trajectory_path = "/tmp/run_arvo_34386_aozf5kr3/results/arvo_34386-1ae0bcc3f813406e8d1a759ad6b5b8c5/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
