[core]
workspace_base = "/tmp/run_arvo_37151_1alv07hy/tmp/arvo_37151-dbd0b2b0c84442b390d885af23d8ade4/workspace"
cache_dir = "/tmp/run_arvo_37151_1alv07hy/results/arvo_37151-dbd0b2b0c84442b390d885af23d8ade4/cache"
file_store_path = "/tmp/run_arvo_37151_1alv07hy/results/arvo_37151-dbd0b2b0c84442b390d885af23d8ade4/file"
save_trajectory_path = "/tmp/run_arvo_37151_1alv07hy/results/arvo_37151-dbd0b2b0c84442b390d885af23d8ade4/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
