[core]
workspace_base = "/tmp/run_arvo_local_secbench_oss_mruby.ossfuzz-42513630_n7qf96bs/workspace"
cache_dir = "/tmp/run_arvo_local_secbench_oss_mruby.ossfuzz-42513630_n7qf96bs/results/secbench_oss_mruby.ossfuzz-42513630-fb961c63016f4af9a38a1f1f7c6a786b/cache"
file_store_path = "/tmp/run_arvo_local_secbench_oss_mruby.ossfuzz-42513630_n7qf96bs/results/secbench_oss_mruby.ossfuzz-42513630-fb961c63016f4af9a38a1f1f7c6a786b/file"
save_trajectory_path = "/tmp/run_arvo_local_secbench_oss_mruby.ossfuzz-42513630_n7qf96bs/results/secbench_oss_mruby.ossfuzz-42513630-fb961c63016f4af9a38a1f1f7c6a786b/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
base_url = ""
temperature = 0.0
top_p = 1.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
