[core]
workspace_base = "/var/folders/np/t4qxz4811lldn6bfqh_sh46c0000gn/T/run_arvo_14620__fu89j06/tmp/arvo_14620-91a62fa61c994e2daf01c944a15e1982/workspace"
cache_dir = "/var/folders/np/t4qxz4811lldn6bfqh_sh46c0000gn/T/run_arvo_14620__fu89j06/results/arvo_14620-91a62fa61c994e2daf01c944a15e1982/cache"
file_store_path = "/var/folders/np/t4qxz4811lldn6bfqh_sh46c0000gn/T/run_arvo_14620__fu89j06/results/arvo_14620-91a62fa61c994e2daf01c944a15e1982/file"
save_trajectory_path = "/var/folders/np/t4qxz4811lldn6bfqh_sh46c0000gn/T/run_arvo_14620__fu89j06/results/arvo_14620-91a62fa61c994e2daf01c944a15e1982/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
