[core]
workspace_base = "/tmp/run_arvo_14501_1akoydhk/tmp/arvo_14501-73be4e1d57a847bfb6ef8ed5d9163839/workspace"
cache_dir = "/tmp/run_arvo_14501_1akoydhk/results/arvo_14501-73be4e1d57a847bfb6ef8ed5d9163839/cache"
file_store_path = "/tmp/run_arvo_14501_1akoydhk/results/arvo_14501-73be4e1d57a847bfb6ef8ed5d9163839/file"
save_trajectory_path = "/tmp/run_arvo_14501_1akoydhk/results/arvo_14501-73be4e1d57a847bfb6ef8ed5d9163839/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
