[core]
workspace_base = "/var/folders/np/t4qxz4811lldn6bfqh_sh46c0000gn/T/run_arvo_16081_p_1kpgtv/tmp/arvo_16081-c7ea3d41ba814fe2a5374f2051fc7ded/workspace"
cache_dir = "/var/folders/np/t4qxz4811lldn6bfqh_sh46c0000gn/T/run_arvo_16081_p_1kpgtv/results/arvo_16081-c7ea3d41ba814fe2a5374f2051fc7ded/cache"
file_store_path = "/var/folders/np/t4qxz4811lldn6bfqh_sh46c0000gn/T/run_arvo_16081_p_1kpgtv/results/arvo_16081-c7ea3d41ba814fe2a5374f2051fc7ded/file"
save_trajectory_path = "/var/folders/np/t4qxz4811lldn6bfqh_sh46c0000gn/T/run_arvo_16081_p_1kpgtv/results/arvo_16081-c7ea3d41ba814fe2a5374f2051fc7ded/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
