[core]
workspace_base = "/tmp/run_arvo_42490980_ni59_9bw/tmp/arvo_42490980-6b870df58ec14b47a83fdef056b5a18c/workspace"
cache_dir = "/tmp/run_arvo_42490980_ni59_9bw/results/arvo_42490980-6b870df58ec14b47a83fdef056b5a18c/cache"
file_store_path = "/tmp/run_arvo_42490980_ni59_9bw/results/arvo_42490980-6b870df58ec14b47a83fdef056b5a18c/file"
save_trajectory_path = "/tmp/run_arvo_42490980_ni59_9bw/results/arvo_42490980-6b870df58ec14b47a83fdef056b5a18c/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
