[core]
workspace_base = "/tmp/run_arvo_10724_lf7admrq/tmp/arvo_10724-2e8a1d1d470f46b79010b2524c9ed99c/workspace"
cache_dir = "/tmp/run_arvo_10724_lf7admrq/results/arvo_10724-2e8a1d1d470f46b79010b2524c9ed99c/cache"
file_store_path = "/tmp/run_arvo_10724_lf7admrq/results/arvo_10724-2e8a1d1d470f46b79010b2524c9ed99c/file"
save_trajectory_path = "/tmp/run_arvo_10724_lf7admrq/results/arvo_10724-2e8a1d1d470f46b79010b2524c9ed99c/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
