[core]
workspace_base = "/tmp/run_arvo_35426_9obnjcte/tmp/arvo_35426-20855ff7a5ad4c209cda4c85358f8da3/workspace"
cache_dir = "/tmp/run_arvo_35426_9obnjcte/results/arvo_35426-20855ff7a5ad4c209cda4c85358f8da3/cache"
file_store_path = "/tmp/run_arvo_35426_9obnjcte/results/arvo_35426-20855ff7a5ad4c209cda4c85358f8da3/file"
save_trajectory_path = "/tmp/run_arvo_35426_9obnjcte/results/arvo_35426-20855ff7a5ad4c209cda4c85358f8da3/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
