[core]
workspace_base = "/tmp/run_arvo_40317_mhageb_a/tmp/arvo_40317-242a6a806cb44006a1ca6077a966d104/workspace"
cache_dir = "/tmp/run_arvo_40317_mhageb_a/results/arvo_40317-242a6a806cb44006a1ca6077a966d104/cache"
file_store_path = "/tmp/run_arvo_40317_mhageb_a/results/arvo_40317-242a6a806cb44006a1ca6077a966d104/file"
save_trajectory_path = "/tmp/run_arvo_40317_mhageb_a/results/arvo_40317-242a6a806cb44006a1ca6077a966d104/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
