[core]
workspace_base = "/tmp/run_arvo_3505_9og1ozb8/tmp/arvo_3505-297a92386fad4ab6ac9bd931ce4ab925/workspace"
cache_dir = "/tmp/run_arvo_3505_9og1ozb8/results/arvo_3505-297a92386fad4ab6ac9bd931ce4ab925/cache"
file_store_path = "/tmp/run_arvo_3505_9og1ozb8/results/arvo_3505-297a92386fad4ab6ac9bd931ce4ab925/file"
save_trajectory_path = "/tmp/run_arvo_3505_9og1ozb8/results/arvo_3505-297a92386fad4ab6ac9bd931ce4ab925/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
