[core]
workspace_base = "/tmp/run_arvo_14331_kp12msll/tmp/arvo_14331-9fafbf80089b4fd7a1b488e1df95c105/workspace"
cache_dir = "/tmp/run_arvo_14331_kp12msll/results/arvo_14331-9fafbf80089b4fd7a1b488e1df95c105/cache"
file_store_path = "/tmp/run_arvo_14331_kp12msll/results/arvo_14331-9fafbf80089b4fd7a1b488e1df95c105/file"
save_trajectory_path = "/tmp/run_arvo_14331_kp12msll/results/arvo_14331-9fafbf80089b4fd7a1b488e1df95c105/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.4-mini"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
