[core]
workspace_base = "/tmp/run_arvo_20286_p3e5sqs3/tmp/arvo_20286-db5d6f1e99304693a0567382c1022e7a/workspace"
cache_dir = "/tmp/run_arvo_20286_p3e5sqs3/results/arvo_20286-db5d6f1e99304693a0567382c1022e7a/cache"
file_store_path = "/tmp/run_arvo_20286_p3e5sqs3/results/arvo_20286-db5d6f1e99304693a0567382c1022e7a/file"
save_trajectory_path = "/tmp/run_arvo_20286_p3e5sqs3/results/arvo_20286-db5d6f1e99304693a0567382c1022e7a/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
