[core]
workspace_base = "/tmp/run_arvo_14821_rxvt06yx/tmp/arvo_14821-7ee6e78e7db94d5ca130ce8ee1b70f2e/workspace"
cache_dir = "/tmp/run_arvo_14821_rxvt06yx/results/arvo_14821-7ee6e78e7db94d5ca130ce8ee1b70f2e/cache"
file_store_path = "/tmp/run_arvo_14821_rxvt06yx/results/arvo_14821-7ee6e78e7db94d5ca130ce8ee1b70f2e/file"
save_trajectory_path = "/tmp/run_arvo_14821_rxvt06yx/results/arvo_14821-7ee6e78e7db94d5ca130ce8ee1b70f2e/trajectory"
run_as_openhands = false

[llm]
model = "claude-opus-4-6"
max_output_tokens = 2048
base_url = "https://api.lmuai.com"
custom_llm_provider = "anthropic"
top_p = 1.0
temperature = 0.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
