[core]
workspace_base = "/tmp/run_arvo_13427_74a6csz2/tmp/arvo_13427-8c527ee310ac4e52ae8851395c4b7c94/workspace"
cache_dir = "/tmp/run_arvo_13427_74a6csz2/results/arvo_13427-8c527ee310ac4e52ae8851395c4b7c94/cache"
file_store_path = "/tmp/run_arvo_13427_74a6csz2/results/arvo_13427-8c527ee310ac4e52ae8851395c4b7c94/file"
save_trajectory_path = "/tmp/run_arvo_13427_74a6csz2/results/arvo_13427-8c527ee310ac4e52ae8851395c4b7c94/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.4-mini"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
