[core]
workspace_base = "/tmp/run_arvo_14141_lz24g2gp/tmp/arvo_14141-cf6b842305894b7bbb7d6c9ae3744817/workspace"
cache_dir = "/tmp/run_arvo_14141_lz24g2gp/results/arvo_14141-cf6b842305894b7bbb7d6c9ae3744817/cache"
file_store_path = "/tmp/run_arvo_14141_lz24g2gp/results/arvo_14141-cf6b842305894b7bbb7d6c9ae3744817/file"
save_trajectory_path = "/tmp/run_arvo_14141_lz24g2gp/results/arvo_14141-cf6b842305894b7bbb7d6c9ae3744817/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
