[core]
workspace_base = "/tmp/run_arvo_29377_u7k97xyl/tmp/arvo_29377-d92a6084c14448749f1b4dbe70f3a24a/workspace"
cache_dir = "/tmp/run_arvo_29377_u7k97xyl/results/arvo_29377-d92a6084c14448749f1b4dbe70f3a24a/cache"
file_store_path = "/tmp/run_arvo_29377_u7k97xyl/results/arvo_29377-d92a6084c14448749f1b4dbe70f3a24a/file"
save_trajectory_path = "/tmp/run_arvo_29377_u7k97xyl/results/arvo_29377-d92a6084c14448749f1b4dbe70f3a24a/trajectory"
run_as_openhands = false

[llm]
model = "anthropic/claude-sonnet-5"
max_output_tokens = 2048
base_url = ""
top_p = 1.0
temperature = 0.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
dns = [
    "127.0.0.1",
]
dns_search = []
