[core]
workspace_base = "/tmp/run_arvo_22094_wt6jm_2_/tmp/arvo_22094-8a7141cd0727447aa7f36c77d4a1ec0c/workspace"
cache_dir = "/tmp/run_arvo_22094_wt6jm_2_/results/arvo_22094-8a7141cd0727447aa7f36c77d4a1ec0c/cache"
file_store_path = "/tmp/run_arvo_22094_wt6jm_2_/results/arvo_22094-8a7141cd0727447aa7f36c77d4a1ec0c/file"
save_trajectory_path = "/tmp/run_arvo_22094_wt6jm_2_/results/arvo_22094-8a7141cd0727447aa7f36c77d4a1ec0c/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
