[core]
workspace_base = "/tmp/run_arvo_58262_vihwi8ib/tmp/arvo_58262-baba7d90fa714b778f785f6bc3a15f7b/workspace"
cache_dir = "/tmp/run_arvo_58262_vihwi8ib/results/arvo_58262-baba7d90fa714b778f785f6bc3a15f7b/cache"
file_store_path = "/tmp/run_arvo_58262_vihwi8ib/results/arvo_58262-baba7d90fa714b778f785f6bc3a15f7b/file"
save_trajectory_path = "/tmp/run_arvo_58262_vihwi8ib/results/arvo_58262-baba7d90fa714b778f785f6bc3a15f7b/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
