[core]
workspace_base = "/tmp/run_arvo_20061_895jup6s/tmp/arvo_20061-dc68d72da2844ecaac746761d92220de/workspace"
cache_dir = "/tmp/run_arvo_20061_895jup6s/results/arvo_20061-dc68d72da2844ecaac746761d92220de/cache"
file_store_path = "/tmp/run_arvo_20061_895jup6s/results/arvo_20061-dc68d72da2844ecaac746761d92220de/file"
save_trajectory_path = "/tmp/run_arvo_20061_895jup6s/results/arvo_20061-dc68d72da2844ecaac746761d92220de/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
