[core]
workspace_base = "/tmp/run_arvo_24528_v9275i0y/tmp/arvo_24528-7b3f46b2aa454b6a9633dec11063196c/workspace"
cache_dir = "/tmp/run_arvo_24528_v9275i0y/results/arvo_24528-7b3f46b2aa454b6a9633dec11063196c/cache"
file_store_path = "/tmp/run_arvo_24528_v9275i0y/results/arvo_24528-7b3f46b2aa454b6a9633dec11063196c/file"
save_trajectory_path = "/tmp/run_arvo_24528_v9275i0y/results/arvo_24528-7b3f46b2aa454b6a9633dec11063196c/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
