[core]
workspace_base = "/tmp/run_arvo_47150_4s44v9ky/tmp/arvo_47150-6e3b969f310145f09f2350073523a2be/workspace"
cache_dir = "/tmp/run_arvo_47150_4s44v9ky/results/arvo_47150-6e3b969f310145f09f2350073523a2be/cache"
file_store_path = "/tmp/run_arvo_47150_4s44v9ky/results/arvo_47150-6e3b969f310145f09f2350073523a2be/file"
save_trajectory_path = "/tmp/run_arvo_47150_4s44v9ky/results/arvo_47150-6e3b969f310145f09f2350073523a2be/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
