[core]
workspace_base = "/tmp/run_arvo_11691_wu44szx3/tmp/arvo_11691-f505a590f8e842cfa87cdd0ff4e58bfa/workspace"
cache_dir = "/tmp/run_arvo_11691_wu44szx3/results/arvo_11691-f505a590f8e842cfa87cdd0ff4e58bfa/cache"
file_store_path = "/tmp/run_arvo_11691_wu44szx3/results/arvo_11691-f505a590f8e842cfa87cdd0ff4e58bfa/file"
save_trajectory_path = "/tmp/run_arvo_11691_wu44szx3/results/arvo_11691-f505a590f8e842cfa87cdd0ff4e58bfa/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
