[core]
workspace_base = "/tmp/run_arvo_16266_8_ll4nmr/tmp/arvo_16266-1c3bbfeb65e34592a4b003a39b13def9/workspace"
cache_dir = "/tmp/run_arvo_16266_8_ll4nmr/results/arvo_16266-1c3bbfeb65e34592a4b003a39b13def9/cache"
file_store_path = "/tmp/run_arvo_16266_8_ll4nmr/results/arvo_16266-1c3bbfeb65e34592a4b003a39b13def9/file"
save_trajectory_path = "/tmp/run_arvo_16266_8_ll4nmr/results/arvo_16266-1c3bbfeb65e34592a4b003a39b13def9/trajectory"
run_as_openhands = false

[llm]
model = "claude-opus-4-6"
max_output_tokens = 2048
base_url = "https://api.lmuai.com"
custom_llm_provider = "anthropic"
top_p = 1.0
temperature = 0.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
