[core]
workspace_base = "/tmp/run_arvo_local_secbench_oss_libxml2.ossfuzz-42509369_kj5am1yq/workspace"
cache_dir = "/tmp/run_arvo_local_secbench_oss_libxml2.ossfuzz-42509369_kj5am1yq/results/secbench_oss_libxml2.ossfuzz-42509369-0b68da53cd174a56b7adf98ef8b67773/cache"
file_store_path = "/tmp/run_arvo_local_secbench_oss_libxml2.ossfuzz-42509369_kj5am1yq/results/secbench_oss_libxml2.ossfuzz-42509369-0b68da53cd174a56b7adf98ef8b67773/file"
save_trajectory_path = "/tmp/run_arvo_local_secbench_oss_libxml2.ossfuzz-42509369_kj5am1yq/results/secbench_oss_libxml2.ossfuzz-42509369-0b68da53cd174a56b7adf98ef8b67773/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
base_url = ""
top_p = 1.0
temperature = 0.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
