[core]
workspace_base = "/tmp/run_arvo_local_secbench_oss_libxml2.ossfuzz-42531481_2vp8qvrr/workspace"
cache_dir = "/tmp/run_arvo_local_secbench_oss_libxml2.ossfuzz-42531481_2vp8qvrr/results/secbench_oss_libxml2.ossfuzz-42531481-8aa44b4771414253a8bdc1ef87767315/cache"
file_store_path = "/tmp/run_arvo_local_secbench_oss_libxml2.ossfuzz-42531481_2vp8qvrr/results/secbench_oss_libxml2.ossfuzz-42531481-8aa44b4771414253a8bdc1ef87767315/file"
save_trajectory_path = "/tmp/run_arvo_local_secbench_oss_libxml2.ossfuzz-42531481_2vp8qvrr/results/secbench_oss_libxml2.ossfuzz-42531481-8aa44b4771414253a8bdc1ef87767315/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
base_url = ""
temperature = 0.0
top_p = 1.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
