[core]
workspace_base = "/tmp/run_arvo_12241_8n6y9c1t/tmp/arvo_12241-adf993c591264f1bbac6ab430d7f3d9b/workspace"
cache_dir = "/tmp/run_arvo_12241_8n6y9c1t/results/arvo_12241-adf993c591264f1bbac6ab430d7f3d9b/cache"
file_store_path = "/tmp/run_arvo_12241_8n6y9c1t/results/arvo_12241-adf993c591264f1bbac6ab430d7f3d9b/file"
save_trajectory_path = "/tmp/run_arvo_12241_8n6y9c1t/results/arvo_12241-adf993c591264f1bbac6ab430d7f3d9b/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
