[core]
workspace_base = "/tmp/run_arvo_18640_bg8c_8qh/tmp/arvo_18640-f9ac76edae1e4132b012603ca6e8c5ef/workspace"
cache_dir = "/tmp/run_arvo_18640_bg8c_8qh/results/arvo_18640-f9ac76edae1e4132b012603ca6e8c5ef/cache"
file_store_path = "/tmp/run_arvo_18640_bg8c_8qh/results/arvo_18640-f9ac76edae1e4132b012603ca6e8c5ef/file"
save_trajectory_path = "/tmp/run_arvo_18640_bg8c_8qh/results/arvo_18640-f9ac76edae1e4132b012603ca6e8c5ef/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
