[core]
workspace_base = "/tmp/run_arvo_10129_jjgdmr9c/tmp/arvo_10129-e3104b24233a4e76941d8ba8484cd503/workspace"
cache_dir = "/tmp/run_arvo_10129_jjgdmr9c/results/arvo_10129-e3104b24233a4e76941d8ba8484cd503/cache"
file_store_path = "/tmp/run_arvo_10129_jjgdmr9c/results/arvo_10129-e3104b24233a4e76941d8ba8484cd503/file"
save_trajectory_path = "/tmp/run_arvo_10129_jjgdmr9c/results/arvo_10129-e3104b24233a4e76941d8ba8484cd503/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.5-2026-04-24"
max_output_tokens = 2048
base_url = "https://aidp.bytedance.net/api/modelhub/online/v2/crawl/openai/deployments/gpt-5.5-2026-04-24/chat/completions?api-version=2024-03-01-preview"
api_version = "2024-03-01-preview"
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
