[core]
workspace_base = "/tmp/run_arvo_42530090_ja2jzbml/tmp/arvo_42530090-8560ad0ddc9a4b43b8b4db56e7b51b7e/workspace"
cache_dir = "/tmp/run_arvo_42530090_ja2jzbml/results/arvo_42530090-8560ad0ddc9a4b43b8b4db56e7b51b7e/cache"
file_store_path = "/tmp/run_arvo_42530090_ja2jzbml/results/arvo_42530090-8560ad0ddc9a4b43b8b4db56e7b51b7e/file"
save_trajectory_path = "/tmp/run_arvo_42530090_ja2jzbml/results/arvo_42530090-8560ad0ddc9a4b43b8b4db56e7b51b7e/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
