[core]
workspace_base = "/tmp/run_arvo_local_osv_ossfuzz_OSV-2025-133_fl05m1ls/workspace"
cache_dir = "/tmp/run_arvo_local_osv_ossfuzz_OSV-2025-133_fl05m1ls/results/osv_ossfuzz_OSV-2025-133-79b175eabe8f4c919f897d4e0d69bfbe/cache"
file_store_path = "/tmp/run_arvo_local_osv_ossfuzz_OSV-2025-133_fl05m1ls/results/osv_ossfuzz_OSV-2025-133-79b175eabe8f4c919f897d4e0d69bfbe/file"
save_trajectory_path = "/tmp/run_arvo_local_osv_ossfuzz_OSV-2025-133_fl05m1ls/results/osv_ossfuzz_OSV-2025-133-79b175eabe8f4c919f897d4e0d69bfbe/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
base_url = ""
temperature = 0.0
top_p = 1.0
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
