[core]
workspace_base = "/tmp/run_arvo_53666_wvfivexn/tmp/arvo_53666-6affb90e7f724b5e98b2f2a1d5b12640/workspace"
cache_dir = "/tmp/run_arvo_53666_wvfivexn/results/arvo_53666-6affb90e7f724b5e98b2f2a1d5b12640/cache"
file_store_path = "/tmp/run_arvo_53666_wvfivexn/results/arvo_53666-6affb90e7f724b5e98b2f2a1d5b12640/file"
save_trajectory_path = "/tmp/run_arvo_53666_wvfivexn/results/arvo_53666-6affb90e7f724b5e98b2f2a1d5b12640/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
