[core]
workspace_base = "/tmp/run_arvo_11730_qwef43lv/tmp/arvo_11730-391ee06b30bc4a12a8325e77ab3e027b/workspace"
cache_dir = "/tmp/run_arvo_11730_qwef43lv/results/arvo_11730-391ee06b30bc4a12a8325e77ab3e027b/cache"
file_store_path = "/tmp/run_arvo_11730_qwef43lv/results/arvo_11730-391ee06b30bc4a12a8325e77ab3e027b/file"
save_trajectory_path = "/tmp/run_arvo_11730_qwef43lv/results/arvo_11730-391ee06b30bc4a12a8325e77ab3e027b/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
