[core]
workspace_base = "/tmp/run_arvo_42481546_j9lqi5an/tmp/arvo_42481546-819f3c8395ae4557bd9cd41579eb1201/workspace"
cache_dir = "/tmp/run_arvo_42481546_j9lqi5an/results/arvo_42481546-819f3c8395ae4557bd9cd41579eb1201/cache"
file_store_path = "/tmp/run_arvo_42481546_j9lqi5an/results/arvo_42481546-819f3c8395ae4557bd9cd41579eb1201/file"
save_trajectory_path = "/tmp/run_arvo_42481546_j9lqi5an/results/arvo_42481546-819f3c8395ae4557bd9cd41579eb1201/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
