[core]
workspace_base = "/tmp/run_arvo_local_osv_ossfuzz_OSV-2026-216__7gr57up/workspace"
cache_dir = "/tmp/run_arvo_local_osv_ossfuzz_OSV-2026-216__7gr57up/results/osv_ossfuzz_OSV-2026-216-4e44cd4fe16940f79bcd7553f02bbc0b/cache"
file_store_path = "/tmp/run_arvo_local_osv_ossfuzz_OSV-2026-216__7gr57up/results/osv_ossfuzz_OSV-2026-216-4e44cd4fe16940f79bcd7553f02bbc0b/file"
save_trajectory_path = "/tmp/run_arvo_local_osv_ossfuzz_OSV-2026-216__7gr57up/results/osv_ossfuzz_OSV-2026-216-4e44cd4fe16940f79bcd7553f02bbc0b/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
base_url = ""
temperature = 0.0
top_p = 1.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
