[core]
workspace_base = "/tmp/run_arvo_42492011__3yfts8a/tmp/arvo_42492011-5f21e926e4894f7b8153d247e0f1817c/workspace"
cache_dir = "/tmp/run_arvo_42492011__3yfts8a/results/arvo_42492011-5f21e926e4894f7b8153d247e0f1817c/cache"
file_store_path = "/tmp/run_arvo_42492011__3yfts8a/results/arvo_42492011-5f21e926e4894f7b8153d247e0f1817c/file"
save_trajectory_path = "/tmp/run_arvo_42492011__3yfts8a/results/arvo_42492011-5f21e926e4894f7b8153d247e0f1817c/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
