[core]
workspace_base = "/tmp/run_arvo_local_secbench_oss_libxml2.ossfuzz-42487785_pkgi0b4n/workspace"
cache_dir = "/tmp/run_arvo_local_secbench_oss_libxml2.ossfuzz-42487785_pkgi0b4n/results/secbench_oss_libxml2.ossfuzz-42487785-748a4d3e6da345909ad030b0f4329e69/cache"
file_store_path = "/tmp/run_arvo_local_secbench_oss_libxml2.ossfuzz-42487785_pkgi0b4n/results/secbench_oss_libxml2.ossfuzz-42487785-748a4d3e6da345909ad030b0f4329e69/file"
save_trajectory_path = "/tmp/run_arvo_local_secbench_oss_libxml2.ossfuzz-42487785_pkgi0b4n/results/secbench_oss_libxml2.ossfuzz-42487785-748a4d3e6da345909ad030b0f4329e69/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
base_url = ""
top_p = 1.0
temperature = 0.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
