[core]
workspace_base = "/tmp/run_arvo_1304_eezxinhl/tmp/arvo_1304-1f51d0f11d0e4418b333ce37b2d26ce7/workspace"
cache_dir = "/tmp/run_arvo_1304_eezxinhl/results/arvo_1304-1f51d0f11d0e4418b333ce37b2d26ce7/cache"
file_store_path = "/tmp/run_arvo_1304_eezxinhl/results/arvo_1304-1f51d0f11d0e4418b333ce37b2d26ce7/file"
save_trajectory_path = "/tmp/run_arvo_1304_eezxinhl/results/arvo_1304-1f51d0f11d0e4418b333ce37b2d26ce7/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
