[core]
workspace_base = "/tmp/run_arvo_42508710_3tv2swko/tmp/arvo_42508710-625f05cc40a2436ba6f20a3532f0e115/workspace"
cache_dir = "/tmp/run_arvo_42508710_3tv2swko/results/arvo_42508710-625f05cc40a2436ba6f20a3532f0e115/cache"
file_store_path = "/tmp/run_arvo_42508710_3tv2swko/results/arvo_42508710-625f05cc40a2436ba6f20a3532f0e115/file"
save_trajectory_path = "/tmp/run_arvo_42508710_3tv2swko/results/arvo_42508710-625f05cc40a2436ba6f20a3532f0e115/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
