[core]
workspace_base = "/tmp/run_arvo_22760_2lcecv69/tmp/arvo_22760-6a24e63c2cf14278ab96eff6755b927a/workspace"
cache_dir = "/tmp/run_arvo_22760_2lcecv69/results/arvo_22760-6a24e63c2cf14278ab96eff6755b927a/cache"
file_store_path = "/tmp/run_arvo_22760_2lcecv69/results/arvo_22760-6a24e63c2cf14278ab96eff6755b927a/file"
save_trajectory_path = "/tmp/run_arvo_22760_2lcecv69/results/arvo_22760-6a24e63c2cf14278ab96eff6755b927a/trajectory"
run_as_openhands = false

[llm]
model = "anthropic/claude-sonnet-5"
max_output_tokens = 2048
base_url = ""
top_p = 1.0
temperature = 0.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
dns = [
    "127.0.0.1",
]
dns_search = []
