[core]
workspace_base = "/tmp/run_arvo_38080_8kst_klk/tmp/arvo_38080-0cf64921ab21403f86236beff7b5f8e1/workspace"
cache_dir = "/tmp/run_arvo_38080_8kst_klk/results/arvo_38080-0cf64921ab21403f86236beff7b5f8e1/cache"
file_store_path = "/tmp/run_arvo_38080_8kst_klk/results/arvo_38080-0cf64921ab21403f86236beff7b5f8e1/file"
save_trajectory_path = "/tmp/run_arvo_38080_8kst_klk/results/arvo_38080-0cf64921ab21403f86236beff7b5f8e1/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
