[core]
workspace_base = "/tmp/run_arvo_local_secbench_oss_mruby.ossfuzz-42532420_cw528xqj/workspace"
cache_dir = "/tmp/run_arvo_local_secbench_oss_mruby.ossfuzz-42532420_cw528xqj/results/secbench_oss_mruby.ossfuzz-42532420-952d07e0ba5848f6b4f3fb0bdb0296cd/cache"
file_store_path = "/tmp/run_arvo_local_secbench_oss_mruby.ossfuzz-42532420_cw528xqj/results/secbench_oss_mruby.ossfuzz-42532420-952d07e0ba5848f6b4f3fb0bdb0296cd/file"
save_trajectory_path = "/tmp/run_arvo_local_secbench_oss_mruby.ossfuzz-42532420_cw528xqj/results/secbench_oss_mruby.ossfuzz-42532420-952d07e0ba5848f6b4f3fb0bdb0296cd/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.5-2026-04-24"
max_output_tokens = 2048
base_url = "https://aidp.bytedance.net/api/modelhub/online/v2/crawl/openai/deployments/gpt_openapi"
api_version = "2024-03-01-preview"
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
dns = [
    "127.0.0.1",
]
dns_search = []
