[core]
workspace_base = "/tmp/run_arvo_local_secbench_oss_openexr.ossfuzz-42538530_myw8ehrk/workspace"
cache_dir = "/tmp/run_arvo_local_secbench_oss_openexr.ossfuzz-42538530_myw8ehrk/results/secbench_oss_openexr.ossfuzz-42538530-0fd1ae7bb9164749b5514af72bfe0c3e/cache"
file_store_path = "/tmp/run_arvo_local_secbench_oss_openexr.ossfuzz-42538530_myw8ehrk/results/secbench_oss_openexr.ossfuzz-42538530-0fd1ae7bb9164749b5514af72bfe0c3e/file"
save_trajectory_path = "/tmp/run_arvo_local_secbench_oss_openexr.ossfuzz-42538530_myw8ehrk/results/secbench_oss_openexr.ossfuzz-42538530-0fd1ae7bb9164749b5514af72bfe0c3e/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
base_url = ""
top_p = 1.0
temperature = 0.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
