[core]
workspace_base = "/tmp/run_arvo_10140_ma7tqg0b/tmp/arvo_10140-5d9f0d431f3b4883973ba8a5c36a7174/workspace"
cache_dir = "/tmp/run_arvo_10140_ma7tqg0b/results/arvo_10140-5d9f0d431f3b4883973ba8a5c36a7174/cache"
file_store_path = "/tmp/run_arvo_10140_ma7tqg0b/results/arvo_10140-5d9f0d431f3b4883973ba8a5c36a7174/file"
save_trajectory_path = "/tmp/run_arvo_10140_ma7tqg0b/results/arvo_10140-5d9f0d431f3b4883973ba8a5c36a7174/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.4-mini"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
