[core]
workspace_base = "/tmp/run_arvo_18004_uzixy9gm/tmp/arvo_18004-4a442c93617b4eb49fa774e287f92140/workspace"
cache_dir = "/tmp/run_arvo_18004_uzixy9gm/results/arvo_18004-4a442c93617b4eb49fa774e287f92140/cache"
file_store_path = "/tmp/run_arvo_18004_uzixy9gm/results/arvo_18004-4a442c93617b4eb49fa774e287f92140/file"
save_trajectory_path = "/tmp/run_arvo_18004_uzixy9gm/results/arvo_18004-4a442c93617b4eb49fa774e287f92140/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
