[core]
workspace_base = "/tmp/run_arvo_61235_6in_0c5s/tmp/arvo_61235-77c24e9d2af44e9faeb8fc5cd821fb55/workspace"
cache_dir = "/tmp/run_arvo_61235_6in_0c5s/results/arvo_61235-77c24e9d2af44e9faeb8fc5cd821fb55/cache"
file_store_path = "/tmp/run_arvo_61235_6in_0c5s/results/arvo_61235-77c24e9d2af44e9faeb8fc5cd821fb55/file"
save_trajectory_path = "/tmp/run_arvo_61235_6in_0c5s/results/arvo_61235-77c24e9d2af44e9faeb8fc5cd821fb55/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
