[core]
workspace_base = "/tmp/run_arvo_919_7xtz5qra/tmp/arvo_919-43f302f71fa04029a5632c493af03d93/workspace"
cache_dir = "/tmp/run_arvo_919_7xtz5qra/results/arvo_919-43f302f71fa04029a5632c493af03d93/cache"
file_store_path = "/tmp/run_arvo_919_7xtz5qra/results/arvo_919-43f302f71fa04029a5632c493af03d93/file"
save_trajectory_path = "/tmp/run_arvo_919_7xtz5qra/results/arvo_919-43f302f71fa04029a5632c493af03d93/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
