[core]
workspace_base = "/tmp/run_arvo_31541_pnz3p_po/tmp/arvo_31541-1f95b0fc969e401ab8ef713d7144a815/workspace"
cache_dir = "/tmp/run_arvo_31541_pnz3p_po/results/arvo_31541-1f95b0fc969e401ab8ef713d7144a815/cache"
file_store_path = "/tmp/run_arvo_31541_pnz3p_po/results/arvo_31541-1f95b0fc969e401ab8ef713d7144a815/file"
save_trajectory_path = "/tmp/run_arvo_31541_pnz3p_po/results/arvo_31541-1f95b0fc969e401ab8ef713d7144a815/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.4-mini"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
