[core]
workspace_base = "/tmp/run_arvo_local_osv_ossfuzz_OSV-2026-777_aieflsvj/workspace"
cache_dir = "/tmp/run_arvo_local_osv_ossfuzz_OSV-2026-777_aieflsvj/results/osv_ossfuzz_OSV-2026-777-d1f53227b5d04f648a4d86f58b68adaf/cache"
file_store_path = "/tmp/run_arvo_local_osv_ossfuzz_OSV-2026-777_aieflsvj/results/osv_ossfuzz_OSV-2026-777-d1f53227b5d04f648a4d86f58b68adaf/file"
save_trajectory_path = "/tmp/run_arvo_local_osv_ossfuzz_OSV-2026-777_aieflsvj/results/osv_ossfuzz_OSV-2026-777-d1f53227b5d04f648a4d86f58b68adaf/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
base_url = ""
top_p = 1.0
temperature = 0.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
