[core]
workspace_base = "/tmp/run_arvo_local_osv_ossfuzz_OSV-2025-373_6iv9ajee/workspace"
cache_dir = "/tmp/run_arvo_local_osv_ossfuzz_OSV-2025-373_6iv9ajee/results/osv_ossfuzz_OSV-2025-373-a98edb6773214860bc37912800773960/cache"
file_store_path = "/tmp/run_arvo_local_osv_ossfuzz_OSV-2025-373_6iv9ajee/results/osv_ossfuzz_OSV-2025-373-a98edb6773214860bc37912800773960/file"
save_trajectory_path = "/tmp/run_arvo_local_osv_ossfuzz_OSV-2025-373_6iv9ajee/results/osv_ossfuzz_OSV-2025-373-a98edb6773214860bc37912800773960/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
base_url = ""
temperature = 0.0
top_p = 1.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
