[core]
workspace_base = "/tmp/run_arvo_12642_s4av_3vo/tmp/arvo_12642-37785a60bad64a3dadd40ca5a8822a8d/workspace"
cache_dir = "/tmp/run_arvo_12642_s4av_3vo/results/arvo_12642-37785a60bad64a3dadd40ca5a8822a8d/cache"
file_store_path = "/tmp/run_arvo_12642_s4av_3vo/results/arvo_12642-37785a60bad64a3dadd40ca5a8822a8d/file"
save_trajectory_path = "/tmp/run_arvo_12642_s4av_3vo/results/arvo_12642-37785a60bad64a3dadd40ca5a8822a8d/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.4-mini"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
