[core]
workspace_base = "/tmp/run_arvo_14141_7xv9bnkt/tmp/arvo_14141-d6426bdca5aa46e5a5d149130b141beb/workspace"
cache_dir = "/tmp/run_arvo_14141_7xv9bnkt/results/arvo_14141-d6426bdca5aa46e5a5d149130b141beb/cache"
file_store_path = "/tmp/run_arvo_14141_7xv9bnkt/results/arvo_14141-d6426bdca5aa46e5a5d149130b141beb/file"
save_trajectory_path = "/tmp/run_arvo_14141_7xv9bnkt/results/arvo_14141-d6426bdca5aa46e5a5d149130b141beb/trajectory"
run_as_openhands = false

[llm]
model = "openai/gpt-5.5-2026-04-24"
max_output_tokens = 2048
base_url = "https://aidp.bytedance.net/api/modelhub/online/v2/crawl/openai/deployments/gpt-5.5-2026-04-24/chat/completions?api-version=2024-03-01-preview"
api_version = "2024-03-01-preview"
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
dns = [
    "127.0.0.1",
]
dns_search = []
