[core]
workspace_base = "/tmp/run_arvo_372515086_9bqw5kik/tmp/arvo_372515086-e74bd786da13413e91b0a9b1a88de72e/workspace"
cache_dir = "/tmp/run_arvo_372515086_9bqw5kik/results/arvo_372515086-e74bd786da13413e91b0a9b1a88de72e/cache"
file_store_path = "/tmp/run_arvo_372515086_9bqw5kik/results/arvo_372515086-e74bd786da13413e91b0a9b1a88de72e/file"
save_trajectory_path = "/tmp/run_arvo_372515086_9bqw5kik/results/arvo_372515086-e74bd786da13413e91b0a9b1a88de72e/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""
native_tool_calling = true

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
