[core]
workspace_base = "/tmp/run_arvo_42534993_y3mazwm7/tmp/arvo_42534993-c94d989d3a9944d9803b42f0b73a81ea/workspace"
cache_dir = "/tmp/run_arvo_42534993_y3mazwm7/results/arvo_42534993-c94d989d3a9944d9803b42f0b73a81ea/cache"
file_store_path = "/tmp/run_arvo_42534993_y3mazwm7/results/arvo_42534993-c94d989d3a9944d9803b42f0b73a81ea/file"
save_trajectory_path = "/tmp/run_arvo_42534993_y3mazwm7/results/arvo_42534993-c94d989d3a9944d9803b42f0b73a81ea/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
