[core]
workspace_base = "/tmp/run_arvo_26674_qdkkzf08/tmp/arvo_26674-45cb4e67b8b340439bd41d9e76182a32/workspace"
cache_dir = "/tmp/run_arvo_26674_qdkkzf08/results/arvo_26674-45cb4e67b8b340439bd41d9e76182a32/cache"
file_store_path = "/tmp/run_arvo_26674_qdkkzf08/results/arvo_26674-45cb4e67b8b340439bd41d9e76182a32/file"
save_trajectory_path = "/tmp/run_arvo_26674_qdkkzf08/results/arvo_26674-45cb4e67b8b340439bd41d9e76182a32/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
