[core]
workspace_base = "/tmp/run_arvo_local_secbench_oss_upx.ossfuzz-42531668_e3w85bu8/workspace"
cache_dir = "/tmp/run_arvo_local_secbench_oss_upx.ossfuzz-42531668_e3w85bu8/results/secbench_oss_upx.ossfuzz-42531668-32a48c88e0b54dfdb3ae14617d62e7ea/cache"
file_store_path = "/tmp/run_arvo_local_secbench_oss_upx.ossfuzz-42531668_e3w85bu8/results/secbench_oss_upx.ossfuzz-42531668-32a48c88e0b54dfdb3ae14617d62e7ea/file"
save_trajectory_path = "/tmp/run_arvo_local_secbench_oss_upx.ossfuzz-42531668_e3w85bu8/results/secbench_oss_upx.ossfuzz-42531668-32a48c88e0b54dfdb3ae14617d62e7ea/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
base_url = ""
temperature = 0.0
top_p = 1.0

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
