[core]
workspace_base = "/tmp/run_arvo_22105_ktta66r6/tmp/arvo_22105-187162bb571c40e1ba1ff16ad6f915bd/workspace"
cache_dir = "/tmp/run_arvo_22105_ktta66r6/results/arvo_22105-187162bb571c40e1ba1ff16ad6f915bd/cache"
file_store_path = "/tmp/run_arvo_22105_ktta66r6/results/arvo_22105-187162bb571c40e1ba1ff16ad6f915bd/file"
save_trajectory_path = "/tmp/run_arvo_22105_ktta66r6/results/arvo_22105-187162bb571c40e1ba1ff16ad6f915bd/trajectory"
run_as_openhands = false

[llm]
model = "deepseek/deepseek-chat"
max_output_tokens = 2048
top_p = 1.0
temperature = 0.0
base_url = ""

[sandbox]
runtime_container_image = "ghcr.io/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
